# NYC traffic accidents over a 4 year period 
## Filter and Subset

Download <a href="https://www.dropbox.com/s/585wrgl08djzlyt/accidents-nyc.csv?dl=0">this dataset</a> stored on dropbox.

In [1]:
## import necessary libraries
import pandas as pd

In [44]:
## read the dataset into notebook
accidents_df = pd.read_csv("data/accidents-nyc.csv")

In [45]:
## see the overall info about this dataset
accidents_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 282873 entries, 0 to 282872
Data columns (total 16 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   CRASH DATE                     282873 non-null  object
 1   CRASH TIME                     282873 non-null  object
 2   BOROUGH                        282873 non-null  object
 3   NUMBER OF PERSONS INJURED      282873 non-null  int64
 4   NUMBER OF PERSONS KILLED       282873 non-null  int64
 5   NUMBER OF PEDESTRIANS INJURED  282873 non-null  int64
 6   NUMBER OF PEDESTRIANS KILLED   282873 non-null  int64
 7   NUMBER OF CYCLIST INJURED      282873 non-null  int64
 8   NUMBER OF CYCLIST KILLED       282873 non-null  int64
 9   NUMBER OF MOTORIST INJURED     282873 non-null  int64
 10  NUMBER OF MOTORIST KILLED      282873 non-null  int64
 11  CONTRIBUTING FACTOR VEHICLE 1  281489 non-null  object
 12  CONTRIBUTING FACTOR VEHICLE 2  224591 non-null  object
 13  COLLISION_ID                   282873 non-null  int64
 14  VEHICLE TYPE CODE 1            279986 non-null  object
 15  VEHICLE TYPE CODE 2            201168 non-null  object
dtypes: int64(9), object(7)
memory usage: 34.5+ MB

In [6]:
## create a series of crash dates.
accidents_df["CRASH DATE"]

0         4/13/21
1         4/13/21
2         4/13/21
3         4/11/21
4         4/15/21
           ...
282868     1/1/19
282869     1/1/19
282870     1/1/19
282871     1/1/19
282872     1/1/19
Name: CRASH DATE, Length: 282873, dtype: object

In [8]:
## Which borough had the most crashes?
accidents_df["BOROUGH"].value_counts()

BROOKLYN         95099
QUEENS           80085
BRONX            50123
MANHATTAN        48864
STATEN ISLAND     8702
Name: BOROUGH, dtype: int64

In [14]:
## which type of vehicle was primary vehicle involved in crashes?
## SHOW ONLY THE TOP 7
accidents_vehicles_df = accidents_df["VEHICLE TYPE CODE 1"].value_counts()
accidents_vehicles_df.head(7)

Sedan                                  129987
Station Wagon/Sport Utility Vehicle    102850
Taxi                                    10647
Pick-up Truck                            7183
Box Truck                                5504
Bus                                      4697
Bike                                     3177
Name: VEHICLE TYPE CODE 1, dtype: int64

In [15]:
## What were a FIVE unusual primary vehicles to get into a crash?
accidents_vehicles_df.tail(5)

SLINGSHOT     1
CHEVY EXPR    1
Go kart       1
FDNY Engin    1
MAC T         1
Name: VEHICLE TYPE CODE 1, dtype: int64

In [20]:
## create a subset of data for only Queens
## place it in a dataframe called df_q
df_q = accidents_df[accidents_df["BOROUGH"] == "QUEENS"]
df_q

,CRASH DATE,CRASH TIME,BOROUGH,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2
0,4/13/21,21:35,QUEENS,1,0,1,0,0,0,0,0,Unspecified,NaN,4407147,Sedan,NaN
1,4/13/21,16:00,QUEENS,0,0,0,0,0,0,0,0,Following Too Closely,Unspecified,4407811,Sedan,NaN
2,4/13/21,17:30,QUEENS,0,0,0,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,4408019,Sedan,Sedan
3,4/11/21,21:06,QUEENS,1,0,1,0,0,0,0,0,Passing Too Closely,NaN,4406488,Taxi,NaN
4,4/15/21,20:00,QUEENS,0,0,0,0,0,0,0,0,Unspecified,NaN,4408310,Sedan,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282868,1/1/19,19:00,QUEENS,0,0,0,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,4060606,Ambulance,Sedan
282869,1/1/19,8:00,QUEENS,0,0,0,0,0,0,0,0,Steering Failure,Unspecified,4060771,Pick-up Truck,Station Wagon/Sport Utility Vehicle
282870,1/1/19,3:30,QUEENS,0,0,0,0,0,0,0,0,Unspecified,Unspecified,4060653,Pick-up Truck,Sedan
282871,1/1/19,19:30,QUEENS,0,0,0,0,0,0,0,0,Passing Too Closely,Unspecified,4268108,Tanker,Sedan
282872,1/1/19,12:00,QUEENS,0,0,0,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,4060666,Sedan,NaN

In [34]:
## CHALLENGE (as in you have to google this)
## How many people were killed in Queens in accidents?
persons_killed_queens_df = df_q["NUMBER OF PERSONS KILLED"].sum()
persons_killed_queens_df

428

In [35]:
## Same
## how many cyclists were killed in Queens?
cyclists_killed_queens_df = df_q["NUMBER OF CYCLIST KILLED"].sum()
cyclists_killed_queens_df

taxi_filter = accidents_df["VEHICLE TYPE CODE 1"] == "Taxi"
manhattan_filter = accidents_df["BOROUGH"] == "MANHATTAN"

[taxi_filter & manhattan_filter]

52

In [47]:
## Filter and subset 
## create a dataset for Manhattan that involved taxi cabs as the primary vehicle cause
taxi_filter = accidents_df["VEHICLE TYPE CODE 1"] == "Taxi"
manhattan_filter = accidents_df["BOROUGH"] == "MANHATTAN"
taxi_manhattan_accidents_df = accidents_df[taxi_filter & manhattan_filter]
taxi_manhattan_accidents_df

,CRASH DATE,CRASH TIME,BOROUGH,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2
67,4/14/21,8:03,MANHATTAN,1,0,1,0,0,0,0,0,Driver Inattention/Distraction,NaN,4407277,Taxi,NaN
144,4/14/21,0:42,MANHATTAN,0,0,0,0,0,0,0,0,Unspecified,Unspecified,4407278,Taxi,Sedan
159,4/16/21,19:54,MANHATTAN,0,0,0,0,0,0,0,0,Unspecified,NaN,4407959,Taxi,NaN
283,4/16/21,21:04,MANHATTAN,0,0,0,0,0,0,0,0,Driver Inattention/Distraction,NaN,4408288,Taxi,NaN
326,4/16/21,16:15,MANHATTAN,0,0,0,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,4408069,Taxi,Bus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282632,1/1/19,1:30,MANHATTAN,0,0,0,0,0,0,0,0,Other Vehicular,Driver Inattention/Distraction,4060445,Taxi,Station Wagon/Sport Utility Vehicle
282684,1/1/19,16:00,MANHATTAN,2,0,0,0,0,0,2,0,Traffic Control Disregarded,Unspecified,4061524,Taxi,Station Wagon/Sport Utility Vehicle
282802,1/1/19,16:15,MANHATTAN,0,0,0,0,0,0,0,0,Passenger Distraction,Passing Too Closely,4060796,Taxi,Sedan
282819,1/1/19,20:30,MANHATTAN,0,0,0,0,0,0,0,0,Unspecified,NaN,4060662,Taxi,NaN
282851,1/1/19,6:00,MANHATTAN,0,0,0,0,0,0,0,0,Unspecified,NaN,4060698,Taxi,NaN

In [49]:
## What were the top 5 causes of accidents across all the boroughs?
## by primary vehicle cause

accidents_df["CONTRIBUTING FACTOR VEHICLE 1"].value_counts().head(6)

Unspecified                       78494
Driver Inattention/Distraction    70615
Failure to Yield Right-of-Way     20691
Following Too Closely             14407
Backing Unsafely                  13348
Passing Too Closely               12048
Name: CONTRIBUTING FACTOR VEHICLE 1, dtype: int64

In [50]:
## What were the top 5 causes of accidents across all the boroughs?
## by secondary vehicle cause
accidents_df["CONTRIBUTING FACTOR VEHICLE 2"].value_counts().head(6)

Unspecified                       190456
Driver Inattention/Distraction     14186
Other Vehicular                     3529
Failure to Yield Right-of-Way       2233
Passing or Lane Usage Improper      2171
Following Too Closely               2131
Name: CONTRIBUTING FACTOR VEHICLE 2, dtype: int64

In [51]:
## What were the 5 RAREST causes for primary vehicles causing the accident
accidents_df["CONTRIBUTING FACTOR VEHICLE 1"].value_counts().tail(5)

Shoulders Defective/Improper    13
Texting                          8
Cell Phone (hands-free)          8
Windshield Inadequate            3
Listening/Using Headphones       2
Name: CONTRIBUTING FACTOR VEHICLE 1, dtype: int64

In [52]:
## list ALL the causes as unique values (in other words, create a list of the causes)
## WHAT ARE SOME UNUSUAL REASONS FOR ACCIDENTS?
join_list = [accidents_df["CONTRIBUTING FACTOR VEHICLE 1"], accidents_df["CONTRIBUTING FACTOR VEHICLE 2"]]
reasons_accidents_df = pd.concat(join_list, sort=True)
reasons_accidents_df

0                            Unspecified
1                  Following Too Closely
2         Driver Inattention/Distraction
3                    Passing Too Closely
4                            Unspecified
                       ...
282868                       Unspecified
282869                       Unspecified
282870                       Unspecified
282871                       Unspecified
282872                       Unspecified
Length: 565746, dtype: object

In [55]:
list(reasons_accidents_df.unique())

['Unspecified',
 'Following Too Closely',
 'Driver Inattention/Distraction',
 'Passing Too Closely',
 'Passing or Lane Usage Improper',
 'Driver Inexperience',
 'Failure to Yield Right-of-Way',
 'Turning Improperly',
 'Unsafe Speed',
 'Backing Unsafely',
 'Steering Failure',
 'Traffic Control Disregarded',
 'Drugs (illegal)',
 'Reaction to Uninvolved Vehicle',
 'View Obstructed/Limited',
 'Pedestrian/Bicyclist/Other Pedestrian Error/Confusion',
 'Alcohol Involvement',
 'Pavement Slippery',
 'Brakes Defective',
 'Oversized Vehicle',
 'Animals Action',
 'Unsafe Lane Changing',
 'Outside Car Distraction',
 'Illnes',
 'Other Vehicular',
 'Aggressive Driving/Road Rage',
 'Fell Asleep',
 'Tire Failure/Inadequate',
 'Pavement Defective',
 nan,
 'Lost Consciousness',
 'Accelerator Defective',
 'Passenger Distraction',
 'Glare',
 'Eating or Drinking',
 'Cell Phone (hands-free)',
 'Lane Marking Improper/Inadequate',
 'Obstruction/Debris',
 'Failure to Keep Right',
 'Using On Board Navigation Device',
 'Fatigued/Drowsy',
 'Physical Disability',
 'Cell Phone (hand-Held)',
 'Headlights Defective',
 'Tinted Windows',
 'Vehicle Vandalism',
 'Driverless/Runaway Vehicle',
 'Prescription Medication',
 'Texting',
 'Traffic Control Device Improper/Non-Working',
 'Tow Hitch Defective',
 'Shoulders Defective/Improper',
 'Windshield Inadequate',
 'Other Lighting Defects',
 'Other Electronic Device',
 'Listening/Using Headphones']

In [56]:
reasons_accidents_df.value_counts()

Unspecified                                              268950
Driver Inattention/Distraction                            84801
Failure to Yield Right-of-Way                             22924
Following Too Closely                                     16538
Backing Unsafely                                          14278
Passing Too Closely                                       13776
Passing or Lane Usage Improper                            13554
Other Vehicular                                           11867
Traffic Control Disregarded                                7340
Turning Improperly                                         6976
Unsafe Speed                                               6425
Unsafe Lane Changing                                       5604
Driver Inexperience                                        5460
Alcohol Involvement                                        3863
Reaction to Uninvolved Vehicle                             3171
View Obstructed/Limited                                    3096
Pedestrian/Bicyclist/Other Pedestrian Error/Confusion      2640
Pavement Slippery                                          1948
Oversized Vehicle                                          1920
Aggressive Driving/Road Rage                               1863
Brakes Defective                                           1075
Passenger Distraction                                       988
Fell Asleep                                                 895
Outside Car Distraction                                     633
Steering Failure                                            544
Obstruction/Debris                                          515
Glare                                                       483
Lost Consciousness                                          415
Illnes                                                      389
Failure to Keep Right                                       372
Driverless/Runaway Vehicle                                  312
Pavement Defective                                          310
Tire Failure/Inadequate                                     292
Fatigued/Drowsy                                             285
Animals Action                                              264
Drugs (illegal)                                             217
Accelerator Defective                                       194
Lane Marking Improper/Inadequate                            171
Traffic Control Device Improper/Non-Working                 166
Cell Phone (hand-Held)                                      117
Physical Disability                                          92
Tinted Windows                                               48
Tow Hitch Defective                                          44
Other Lighting Defects                                       39
Headlights Defective                                         39
Vehicle Vandalism                                            35
Prescription Medication                                      34
Eating or Drinking                                           25
Using On Board Navigation Device                             24
Other Electronic Device                                      24
Shoulders Defective/Improper                                 14
Cell Phone (hands-free)                                      11
Texting                                                       9
Listening/Using Headphones                                    8
Windshield Inadequate                                         3
dtype: int64

In [57]:
unusual_accidents_df = ["Prescription Medication","Tinted Windows","Eating or Drinking","Listening/Using Headphones","Texting"]
list(unusual_accidents_df)

['Prescription Medication',
 'Tinted Windows',
 'Eating or Drinking',
 'Listening/Using Headphones',
 'Texting']